version: "3"
services:
    influxdb:
        image: influxdb:2.7
        container_name: influxdb
        restart: unless-stopped
        ports:
            - ${INFLUXDB_PORT}:8086
        volumes:
            - ./influxdb:/var/lib/influxdb2
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_ADMIN_USER}
            DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
            DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
            DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}

    grafana:
        image: grafana/grafana-oss:10.2.2
        container_name: grafana
        restart: unless-stopped
        ports:
            - ${GRAFANA_PORT}:3000
        volumes:
            - ./grafana/data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/dashboards:/var/lib/grafana/dashboards
        environment:
            GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
            GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
            GF_USERS_ALLOW_SIGN_UP: "false"
            GF_USERS_AUTO_ASSIGN_ORG: "true"
            GF_USERS_AUTO_ASSIGN_ORG_ROLE: "Admin"
            GF_AUTH_ANONYMOUS_ENABLED: "true"
            GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
            GF_AUTH_ANONYMOUS_ORG_NAME: ${INFLUXDB_ORG}
            GF_AUTH_ANONYMOUS_USER: ${GRAFANA_ANONYMOUS_USER}
            GF_AUTH_ANONYMOUS_PASSWORD: ${GRAFANA_ANONYMOUS_PASSWORD}
            INFLUXDB_URL: "http://influxdb:${INFLUXDB_PORT}"
            INFLUXDB_ORG: ${INFLUXDB_ORG}
            INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
            INFLUXDB_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
        depends_on:
            - influxdb
        user: ":"

    nala:
        image: nala:latest
        container_name: nala
        restart: unless-stopped
        ports:
            - ${NALA_PORT}:8088
        environment:
            GIN_MODE: release
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: ${INFLUXDB_PORT}
            INFLUXDB_ORG: ${INFLUXDB_ORG}
            INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
            INFLUXDB_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
        depends_on:
            - influxdb

networks:
    default:
        name: pdc-mad
