{
 "title": "Anomaly Overview",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Field",
    "query": "SHOW FIELD KEYS FROM \"metrics\""
   },
   {
    "name": "System",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "Algorithm",
    "query": "SHOW TAG VALUES WITH KEY = \"algorithm\""
   }
  ]
 },
 "panels": [
  {
   "title": "Anomalies on $System: $Field",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Anomalies",
     "measurement": "anomalies",
     "select": [
      [
       { "params": [ "$Field" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "algorithm::tag", "operator": "=~", "value": "/^$Algorithm$/" }
     ]
    },
    {
     "alias": "Metrics",
     "query": "SELECT mean(\"$Field\") FROM \"metrics\" WHERE (\"host\"::tag =~ /^$System$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "$System.$Field",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metrics",
     "query": "SELECT mean(\"$Field\") FROM \"metrics\" WHERE (\"host\"::tag =~ /^$System$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "$Field" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Overview of $System",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 12 },
   "targets": [
    {
     "measurement": "anomalies",
     "query": "SELECT * FROM \"anomalies\" WHERE (\"host\"::tag =~ /^$System$/) AND (\"algorithm\"::tag =~ /^$Algorithm$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "$Algorithm: Anomalies on $Field across systems",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "anomalies",
     "query": "SELECT COUNT(\"$Field\") FROM \"anomalies\" WHERE \"$Field\" = true AND (\"algorithm\"::tag =~ /^$Algorithm$/) AND $timeFilter GROUP BY \"host\"::tag",
     "select": [
      [
       { "params": [ "$Field" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}